# -*- coding: utf-8 -*-
"""[DATASCI] DataCollection_Bulbapedia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tULG_Wj6O8_mBTQ1lwpVk7M4lCstSRMT
"""

import requests
from bs4 import BeautifulSoup
from google.colab import files
import json

URL = "https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number"
page = requests.get(URL)
soup = BeautifulSoup(page.content, 'html.parser')

poke_content = soup.find(id='mw-content-text')
poke_tables = poke_content.find_all('table')

j=0
allgens_JSON = []

info_start=3

while(j<10):
  j+=1
  allgens_list = poke_tables[j]
  for i in range(info_start, len(allgens_list.contents), 2):
      poke_info=allgens_list.contents[i]
      kdex=poke_info.contents[1].text.strip()
      ndex=poke_info.contents[3].text.strip()
      name=poke_info.contents[7].text.strip()
      type1=poke_info.contents[9].text.strip()
      if len(poke_info.contents) > 10:
          type2=poke_info.contents[11].text.strip()
          allgens_JSON.append({
            "kdex": kdex,
            "ndex": ndex,
            "name": name,
            "type1": type1,
            "type2": type2
          })
      else:
          allgens_JSON.append({
            "kdex": kdex,
            "ndex": ndex,
            "name": name,
            "type1": type1
          })


with open('allgens.json', 'w', encoding='utf-8') as f:
  json.dump(allgens_JSON, f, ensure_ascii=False, indent=4)

files.download('allgens.json')